export const AsciiLogo = [
  "  _ _      __  __    ____  ___   ____ ",
  " | | |    |  \\/  |  |  _ \\|  _ \\|  _ \\",
  " | | |    | |\\/| |  | | | | | | | | | |",
  " | | |__  | |  | |  | |_| | |_| | |_| |",
  " |_|____| |_|  |_|  |____/|____/|____/",
].join("\n");

export const BrandInfo = [
  "",
  "  LiMa Code — 深圳市动力巢科技有限公司出品",
  "  LiMa Code by DongLiCao Tech (Shenzhen)",
  "",
  "  特点 Features:",
  "  · 智能路由 80+ AI 后端，自动选择最优模型",
  "  · Smart routing across 80+ AI backends",
  "  · 深度集成 LiMa Server：代码上下文注入 + 学习闭环",
  "  · Deep LiMa Server integration: context injection + learning loop",
  "  · 支持 Python/JS/TS/Go/Rust/Java 多语言代码理解",
  "  · Multi-language code understanding (Python/JS/TS/Go/Rust/Java)",
  "  · 本地工具执行：bash/read/write/edit + MCP 扩展",
  "  · Local tool execution: bash/read/write/edit + MCP extensions",
  "",
  "  解决 Problems Solved:",
  "  · 编码助手后端统一管理，无需手动切换模型",
  "  · Unified coding assistant backend, no manual model switching",
  "  · 自动故障转移，单后端挂了不影响工作",
  "  · Auto failover — single backend failure won't block your work",
  "  · 代码上下文自动注入，回答更精准",
  "  · Auto code context injection for more accurate answers",
  "",
].join("\n");
