export function buildCliHelpText(): string {
  return (
    [
      "lima-code - LiMa Code 命令行助手",
      "",
      "用法：",
      "  lima-code                             在当前目录启动交互式 TUI",
      "  lima-code -p <prompt>                 带预填提示词启动",
      "  lima-code --prompt <prompt>           同 -p",
      "  lima-code --headless -p <prompt>      无 TUI 执行一次提示词",
      "  lima-code --headless -p <p> --json    无 TUI 执行并输出 JSON",
      "  lima-code --headless                  无 TUI 交互模式（逐行读取 stdin）",
      "  lima-code --daemon                    daemon 模式：轮询 LiMa Server 任务",
      "  lima-code --version                   打印版本号",
      "  lima-code --help                      显示帮助",
      "",
      "配置：",
      "  ~/.lima-code/settings.json   用户级 API key、模型、base URL",
      "  ./.lima-code/settings.json   项目级设置",
      "  ~/.deepcode/settings.json    旧版兼容配置（已废弃）",
      "  ./.deepcode/settings.json    旧版兼容配置（已废弃）",
      "",
      "TUI 内快捷键：",
      "  enter            发送提示词",
      "  shift+enter      插入换行",
      "  ctrl+v           从剪贴板粘贴图片",
      "  esc              中断当前模型回合",
      "  /                打开命令菜单",
      "",
      "聊天命令：",
      "  /skills          列出可用技能",
      "  /model           选择模型、思考模式和推理强度",
      "  /new             开启新对话",
      "  /init            初始化 AGENTS.md 项目指令",
      "  /resume          选择历史对话继续",
      "  /continue        继续当前对话",
      "  /undo            回退代码或对话到历史节点",
      "  /mcp             查看 MCP 服务状态和工具",
      "  /raw             切换显示模式（精简/普通/原始回滚）",
      "",
      "LiMa Worker 命令：",
      "  /lima connect    检查 LiMa Server 连接配置",
      "  /lima status     查看 worker 状态",
      "  /lima start      显示项目工作台",
      "  /lima doctor     检查本地配置",
      "  /lima plan       生成实施计划",
      "  /lima test       运行测试",
      "  /lima fix        修复问题",
      "  /lima next       获取下一项任务",
      "  /lima audit      查看近期审计记录",
      "  /lima work       自动工作循环",
      "  /lima task       查看任务详情",
      "  /lima review     审查代码",
      "  /lima ship       交付前检查",
      "",
      "  /exit            退出",
      "  ctrl+d 两次      退出",
    ].join("\n") + "\n"
  );
}
